---
- hosts: node6
  tasks:
    - name: Instalar Apache
      yum: 
        name: httpd
        state: latest
    
    - name: Iniciando Servicios
      service:
        name: "{{ item }}"
        enabled: true
        state: started 
      with_items:
        - httpd

    - name: Copiando contenido
      copy:
        content: "Bienvenido a mi Web!"
        dest: /var/www/html/index.html

    - name: Deshabilitando FW
      service:
        name: firewalld
        state: stopped
        enabled: false


